name = "nuxt-dtako-logs"
compatibility_date = "2024-09-19"
main = "./.output/server/index.mjs"
assets = { directory = "./.output/public/", binding = "ASSETS" }

# Service Binding: cf-grpc-proxyのDurable Objectに接続
[[services]]
binding = "GRPC_PROXY_SERVICE"
service = "cf-grpc-proxy"
